version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    env_file:
      - app/env/.env
      - app/env/.uvicorn.env
    ports:
      - "4001:4001"
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4001" ]
    volumes:
      - ./app:/usr/src/app:cached
      - pip_cache:/root/.cache
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4001/health" ]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mariadb:latest
    container_name: app_db
    env_file:
      - app/env/.mariadb.env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - backups:/backups
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    container_name: app-adminer
    depends_on:
      - db
    env_file:
      - app/env/.env
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    container_name: app_redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_celery
    command: celery -A celery worker --loglevel=info
    depends_on:
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_celery_beat
    command: celery -A celery beat --loglevel=info
    depends_on:
      - redis
      - db

volumes:
  pip_cache:
  db:
  backups:
